name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: clang-format Check
      uses: jidicula/clang-format-action@v4.9.0
      with:
        # The version of clang-format that you want to use.
        clang-format-version: '13'
        exclude-regex: '(benchmark|googletest)'

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-artifacts
        path: .
        if-no-files-found: error
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: build-artifacts
        
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests/tests --gtest_filter=-CliqueTest.*
      
